import type { Metadata } from "next";
import { Inter, Open_Sans, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { Header } from '@/components/layout/Header'
import { navButtons, navItems } from '@/components/ui/header/navItems'

// const openSans = Open_Sans({
//   subsets: ["latin"],
//   weight: '700'
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang='en'>
			<body className={`bg-[#F1F2F6] overflow-x-hidden`}>
				<Header navItems={navItems} navButtons={navButtons} />
				{children}
			</body>
		</html>
	)
}
