import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import { Header } from '@/components/layout/Header'
import { navButtons, navItems } from '@/components/ui/header/navItems'

const roboto = Roboto({
  subsets: ["latin"],
  weight: '700'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang='en'>
			<body className={`${roboto.className} bg-[#f3f3f5] overflow-x-hidden`}>
				<Header navItems={navItems} navButtons={navButtons} />
				{children}
			</body>
		</html>
	)
}
