name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.18.0]
        
    env: 
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}      
      NEXT_WEBSITE_URL: ${{ secrets.NEXT_WEBSITE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Set up swap (2GB)
        # Этот шаг добавляет временный swap-файл для предотвращения нехватки памяти
        run: |
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h  # Проверяем доступную память
      
      - name: Install dependencies with npm (limited concurrency)
        # Увеличение выделенной памяти для Node.js и ограничение параллелизма
        run: |
          node --max-old-space-size=4096 $(which npm) install --prefer-offline --concurrency=1
          
      - name: Build project
        run: npm run build --if-present

      - name: Remove swap
        # Удаление swap-файла после завершения работы
        if: always()
        run: |
          sudo swapoff /swapfile
          sudo rm /swapfile
